# -*- coding: utf-8 -*-
"""AI UI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D60hLMFQA6xlO-RiP925DeqCNOrrYD-k
"""

import time
import joblib
import numpy as np
import gradio as gr

# Load model and label encoder
start_time = time.time()
pipeline = joblib.load("RandomForest.pkl")
label_encoder = joblib.load("label_encoder.pkl")
end_time = time.time()
print(f"Model loaded in {end_time - start_time:.2f} seconds.")

# Define your model's accuracy (from evaluation)
MODEL_ACCURACY = 0.84  # 84% example

def predict_fn(monthly_inhand_salary, num_bank_accounts, num_credit_card, interest_rate,
               delay_from_due_date, num_of_delayed_payment, changed_credit_limit,
               num_credit_inquiries, credit_utilization_ratio, total_emi_per_month,
               amount_invested_monthly, monthly_balance, credit_history_age_months,
               month_num, num_loan_types):
    try:
        print("Received inputs:", monthly_inhand_salary, num_bank_accounts, num_credit_card,
              interest_rate, delay_from_due_date, num_of_delayed_payment, changed_credit_limit,
              num_credit_inquiries, credit_utilization_ratio, total_emi_per_month,
              amount_invested_monthly, monthly_balance, credit_history_age_months,
              month_num, num_loan_types)

        # Create data array for prediction
        data = np.array([[monthly_inhand_salary, num_bank_accounts, num_credit_card,
                          interest_rate, delay_from_due_date, num_of_delayed_payment,
                          changed_credit_limit, num_credit_inquiries, credit_utilization_ratio,
                          total_emi_per_month, amount_invested_monthly, monthly_balance,
                          credit_history_age_months, month_num, num_loan_types]])

        # Make prediction
        prediction = pipeline.predict(data)
        print("Prediction result:", prediction)

        # Convert label if encoded
        if isinstance(prediction[0], str):
            label = prediction[0]
        else:
            label = label_encoder.inverse_transform(prediction)[0]

        # Return label + accuracy
        return f"Predicted Credit Mix: {label} | Model Accuracy: {MODEL_ACCURACY*100:.2f}%"

    except Exception as e:
        print("❌ Error during prediction:", str(e))
        return f"Error: {str(e)}"

# Gradio Interface (unchanged)
iface = gr.Interface(
    fn=predict_fn,
    inputs=[
        gr.Number(label="Monthly Inhand Salary"),
        gr.Number(label="Number of Bank Accounts"),
        gr.Number(label="Number of Credit Cards"),
        gr.Number(label="Interest Rate"),
        gr.Number(label="Delay from Due Date"),
        gr.Number(label="Number of Delayed Payment"),
        gr.Number(label="Changed Credit Limit"),
        gr.Number(label="Number of Credit Inquiries"),
        gr.Number(label="Credit Utilization Ratio"),
        gr.Number(label="Total EMI per Month"),
        gr.Number(label="Amount Invested Monthly"),
        gr.Number(label="Monthly Balance"),
        gr.Number(label="Credit History Age (Months)"),
        gr.Number(label="Month Number"),
        gr.Number(label="Number of Loan Types"),
    ],
    outputs="text",
    title="Credit Loan Prediction App",
    description="Enter financial details to predict the customer's Credit Mix (Good, Standard, Bad)."
)

iface.launch()